### ISSUE TITLE
Tested Reolink: succes

### ISSUE THREAD

**Issue by CFTechno** [amancini/ONVIF4Delphi#16]
Run the demo on a Reolink TrackMix POE, no problem
![afbeelding](https://github.com/amancini/ONVIF4Delphi/assets/4393636/655ad313-f683-466b-b742-d945e57cc685)

If you need more info/testing let me known.

**Comment by amancini** [comment]
thanks can I add it as a tested device in the realm of GitHub?

**Comment by CFTechno** [comment]
Yes, no problem, i also have another reolink type camera 
![afbeelding](https://github.com/amancini/ONVIF4Delphi/assets/4393636/457cf918-44ba-4298-99f0-9f644c04602c)
reolink RLC-812A (also POE)
